# Generated by Django 4.0.4 on 2022-05-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordDigest',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
