# Generated by Django 4.0.4 on 2022-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0004_membership_remove_user_group_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, through='groupchat.Membership', to='groupchat.group'),
        ),
    ]
