# Generated by Django 4.0.4 on 2022-05-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0005_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
