# Generated by Django 4.0.4 on 2022-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0007_alter_membership_group_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.IntegerField(),
        ),
    ]
