# Generated by Django 4.0.4 on 2022-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0008_alter_membership_group_alter_membership_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('user', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('message', models.IntegerField()),
            ],
        ),
    ]
