# Generated by Django 4.0.4 on 2022-05-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0009_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
