# Generated by Django 4.0.4 on 2022-05-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0014_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
