# Generated by Django 4.0.4 on 2022-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0015_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
