# Generated by Django 4.0.4 on 2022-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0017_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groupColor',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
