# Generated by Django 4.0.4 on 2022-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0018_post_groupcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField()),
                ('comment', models.TextField()),
                ('user', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
