# Generated by Django 4.0.4 on 2022-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0020_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='laughs',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
