# Generated by Django 4.0.4 on 2022-05-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0023_comment_dislikes_comment_laughs_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
