# Generated by Django 4.0.4 on 2022-05-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0024_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
