# Generated by Django 4.0.4 on 2022-05-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0025_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
